name: Build Av1an (Windows x64)
on:
  push:
    branches:
      - 'master'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    env:
      CARGO_INCREMENTAL: 0
      FFMS_LIB_DIR: ${{github.workspace}}\ffms2-5.0-msvc\x64
      FFMS_INCLUDE_DIR: ${{github.workspace}}\ffms2-5.0-msvc\include

    steps:
      - name: NASM setup
        uses: ilammy/setup-nasm@v1
        with:
          # version: 2.16.03
          from-source: false

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: 3.14
          activate-environment: true

      - name: VapourSynth Python package installation
        run: |
          uv pip install vapoursynth==74
          vapoursynth config
          "VSSCRIPT_PATH=$(vapoursynth get-vsscript)" >> "$env:GITHUB_ENV"

      - name: FFMS2 installation
        run: |
          curl -L -o ffms2.7z "https://github.com/FFMS/ffms2/releases/download/5.0/ffms2-5.0-msvc.7z"
          7z x ffms2.7z

      - uses: actions/checkout@v6

      - uses: Swatinem/rust-cache@v2

      - name: Get latest commit
        id: get_commit
        shell: pwsh
        run: |
          $commit = git log -1 --pretty=format:"%h: %s (%an)"
          echo "message=$commit" >> $env:GITHUB_OUTPUT
      - name: Av1an build
        run: cargo build --release

      - name: Create or update prerelease
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: latest
          body: |
            Latest build from ${{ github.sha }}

            Commit:
            ${{ steps.get_commit.outputs.message }}
          files: target/release/av1an.exe
          fail_on_unmatched_files: true

      - name: Condor build
        run: cargo build --release --bin condor

      - name: Create or update prerelease for Condor
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: latest-condor
          body: |
            Latest build from ${{ github.sha }}

            Commit:
            ${{ steps.get_commit.outputs.message }}
          files: target/release/condor.exe
          fail_on_unmatched_files: true
